name: Build  Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo’yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Docker image build
      - name: Build Docker image
        run: docker build -t my-html-app .

      # 4️⃣ Docker image tag
      - name: Tag Docker image
        run: docker tag my-html-app ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
