name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

    steps:
      # 1️⃣ Repo’yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Docker image build
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/my-html-app:latest .
          docker push $DOCKER_USERNAME/my-html-app:latest

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
